/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BlogPostSchema extends BaseModel {
  static $columns = ['binanceEmbedUrl', 'binanceSymbol', 'content', 'createdAt', 'excerpt', 'id', 'publishedAt', 'slug', 'tags', 'title', 'updatedAt'] as const
  $columns = BlogPostSchema.$columns
  @column()
  declare binanceEmbedUrl: string | null
  @column()
  declare binanceSymbol: string | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare tags: any
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ContactInquirySchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'message', 'name', 'relatedPostSlug', 'sentAt', 'sourcePage', 'status', 'subject', 'updatedAt'] as const
  $columns = ContactInquirySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare message: string
  @column()
  declare name: string
  @column()
  declare relatedPostSlug: string | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare sourcePage: string | null
  @column()
  declare status: string
  @column()
  declare subject: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PortfolioEntrySchema extends BaseModel {
  static $columns = ['context', 'coverImageUrl', 'createdAt', 'detailsHtml', 'endDate', 'externalLinks', 'highlighted', 'id', 'impactMetrics', 'slug', 'sortOrder', 'stack', 'startDate', 'summary', 'title', 'type', 'updatedAt'] as const
  $columns = PortfolioEntrySchema.$columns
  @column()
  declare context: string | null
  @column()
  declare coverImageUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detailsHtml: string | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare externalLinks: any
  @column()
  declare highlighted: boolean
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare impactMetrics: any
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare stack: any
  @column.date()
  declare startDate: DateTime | null
  @column()
  declare summary: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
